# Values below are the tuned settings used for the published results.
unlearner: "neggrad"
mode: "per_subject"

unlearner_config:
  num_epochs: 10
  batch_size_forget: 8
  batch_size_retain: 8
  val_check_interval: 50
  gradient_clip_val: 0.6215214492367136
  num_workers: 4
  pin_memory: false
  test_loss_mean: null

  optimizer:
    type: "adam"
    lr: 2.594858841506273e-07
    weight_decay: 1.0e-06
    betas: [0.9, 0.999]

  early_stopping:
    active: false
    monitor: train/forget_task
    stopping_threshold: 100
    patience: 2
    min_delta: 10
    mode: max

  # NegGrad-specific
  threshold: 0.9673789487242912
  cycle_length: 5
  batches_to_check: 5
